name: "Run Workflow"
on:
  workflow_dispatch:

jobs:
  startRemove:
    runs-on: ubuntu-latest
    steps:
      - name: "CheckRepo"
        uses: actions/checkout@v4

      - name: "CondaEnv"
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: wftenv
          python-version: "3.7"
          
      - name: "ReleasesPatch"
        uses: robinraju/release-downloader@v1
        with:
          repository: "Toad114514/DeepCreamPy"
          fileName: "09-11-2019.DCPv2.model.zip"
          out-file-path: "./unpack"
          extract: false
          tag: "bar_models"
          token: ${{ secrets.MY_PRIVATE_TOKEN }}
      
      - name: "RunScript"
        env:
          MY_TOKEN: ${{ secrets.MY_PRIVATE_TOKEN }}
        shell: bash -el {0}
        run: |
          chmod +x ./start.sh
          ./start.sh

      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
           name: uploaded
           path: ./decensor_output
           retention-days: 7
